services:
  - type: web
    name: fastapi-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SUPABASE_URL
        value: https://xzgairkkaauiqwqcuzrx.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6Z2FpcmtrYWF1aXF3cWN1enJ4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDQ0MTk5MywiZXhwIjoyMDY2MDE3OTkzfQ.UuWi7adIJ72v3DICU9E-uuS6SfLQ52zBmKMvWlpBNKg
      - key: SUPABASE_BUCKET
        value: testbucket
